# Generated by Django 4.2.7 on 2023-11-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_company_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tech_stack',
        ),
        migrations.RemoveField(
            model_name='company',
            name='welfare',
        ),
        migrations.AlterField(
            model_name='company',
            name='loc_info_id',
            field=models.ForeignKey(db_column='loc_info_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.locationinfo'),
        ),
        migrations.AlterField(
            model_name='companytechmapping',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.company'),
        ),
        migrations.AlterField(
            model_name='companytechmapping',
            name='tech_id',
            field=models.ForeignKey(db_column='tech_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.techstack'),
        ),
        migrations.AlterField(
            model_name='companywelfaremapping',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.company'),
        ),
        migrations.AlterField(
            model_name='companywelfaremapping',
            name='welfare_id',
            field=models.ForeignKey(db_column='welfare_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.welfare'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='loc_info_id',
            field=models.ForeignKey(db_column='loc_info_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='data.locationinfo'),
        ),
        migrations.AlterField(
            model_name='jobpositionmapping',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.job'),
        ),
        migrations.AlterField(
            model_name='jobpositionmapping',
            name='position_id',
            field=models.ForeignKey(db_column='position_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.position'),
        ),
        migrations.AlterField(
            model_name='jobtechmapping',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.job'),
        ),
        migrations.AlterField(
            model_name='jobtechmapping',
            name='tech_id',
            field=models.ForeignKey(db_column='tech_id', on_delete=django.db.models.deletion.DO_NOTHING, to='data.techstack'),
        ),
    ]
